version: "3"
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - db_data:/home/dynamodblocal
    restart: always
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
